t_scene_info=[
	[cutscene_move_character,obj_everett,598,248,false,1],
	[cutscene_play_sound,snd_dooropen,50,false],
	[cutscene_instance_destroy,obj_everett],
	[cutscene_wait,1],
	[cutscene_play_sound,snd_doorshut,50,false],
	[cutscene_instance_create,328,266,"Objects",obj_everett],
	[cutscene_wait,.5],
	[cutscene_move_character,obj_everett,-16,0,true,1],
];